# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_auto_20170727_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='last_run',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='queryinstance',
            name='root_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='queryinstance',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='queryinstance',
            name='visual_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
