# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_auto_20170728_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryinstance',
            name='root_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
