# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_auto_20170728_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='query_text',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='queries',
            name='schedule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='queryinstance',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
